services:
  frontend:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 512M
    memswap_limit: 4G
    ports:
      - '3002:3002'
    environment:
      - NODE_ENV=production
      - PORT=3002
      - NODE_OPTIONS=--max-old-space-size=4096
