services:
  frontend:
    restart: always
    image: girls-in-armor
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 512M
    ports:
      - '3002:3002'
    environment:
      - NODE_ENV=production
      - PORT=3002
      - NODE_OPTIONS=--max-old-space-size=4096
